version: '2'
services:
  poll:
    container_name: 'poll'
    build: .
    command: python3 /code/mysite/manage.py runserver

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./nginx/tls:/etc/nginx/tls"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"
